### ISSUE TITLE
[Bug]: fail to install miactl

### ISSUE THREAD

**Issue by danibix95** [mia-platform/miactl#113]
### What version or versions you have tested?

0.7.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### What did you expect to happen?

Being able to install `miactl` via the command described in the documentation:

    go install github.com/mia-platform/miactl@0.7.0

### What happened instead?

I tried to install the `miactl` following the [setup documentation](https://docs.mia-platform.eu/docs/cli/miactl/setup). However, when I execute the following command

    go install github.com/mia-platform/miactl@0.7.0

I receive this error and miactl is not locally installed:

    go: github.com/mia-platform/miactl@0.7.0: github.com/mia-platform/miactl@0.7.0: invalid version: unknown revision 0.7.0

I also tried adding the `v` prefix to the version, since all the releases/tags start with `v`:

    go install github.com/mia-platform/miactl@v0.7.0

but I obtain another error:

    go: github.com/mia-platform/miactl@v0.7.0: module github.com/mia-platform/miactl@v0.7.0 found, but does not contain package github.com/mia-platform/miactl

Finally, I also tried to install via `go get`:

    go get -u github.com/mia-platform/miactl@0.7.0

but another error is reported:

    go: go.mod file not found in current directory or any parent directory.
	    'go get' is no longer supported outside a module.
	    To build and install a command, use 'go install' with a version,
	    like 'go install example.com/cmd@latest'
	    For more information, see https://golang.org/doc/go-get-install-deprecation
	    or run 'go help get' or 'go help install'.
---

Linux: `Ubuntu 22.04.3 LTS`
Go version: `go1.21.2 linux/amd64`
GOPATH: `~/.asdf/installs/golang/1.21.2/packages`

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by malta895** [comment]
Hi @danibix95,
the right command is `go install github.com/mia-platform/miactl/cmd/miactl@v0.7.0`, the subpackage `cmd/miactl` has to be added.

I don't know if this is intended or if the doc is wrong, maybe @JGiola can help us on this matter
